### ISSUE TITLE
golint cleanup

### ISSUE THREAD

**Issue by dougnukem** [codingsince1985/geo-golang#15]
https://goreportcard.com/report/github.com/codingsince1985/geo-golang#golint

> `$ golint ./...`
> geocoder.go:16:5: var timeoutInSeconds is of type time.Duration; don't use unit-specific suffix "Seconds"
> mapbox/geocoder.go:14:3: don't use underscores in Go names; struct field Place_Name should be PlaceName
> mapquest/nominatim/geocoder.go:13:2: don't use underscores in Go names; struct field Display_Name should be DisplayName
> openstreetmap/geocoder.go:14:2: don't use underscores in Go names; struct field Display_Name should be DisplayName
>

**Comment by codingsince1985** [comment]
fixed in commit b2019348fa9afdf000504770860bb075f50a6184
