### ISSUE TITLE
Panic in mapquest/open/geocoder.go

### ISSUE THREAD

**Issue by saheljalal** [codingsince1985/geo-golang#30]
I have a test that uses lat/long 0,0 and it seems to panic the library.

panic: runtime error: index out of range

goroutine 76 [running]:
panic(0x39cd00, 0xc4200140f0)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
../vendor/github.com/codingsince1985/geo-golang/mapquest/open.(*geocodeResponse).Address(0xc42043c5c0, 0x50, 0x5cd2e0)
	../vendor/github.com/codingsince1985/geo-golang/mapquest/open/geocoder.go:49 +0x18a
../vendor/github.com/codingsince1985/geo-golang.HTTPGeocoder.ReverseGeocode.func1(0x5ce920, 0xc4200156f0, 0x444178, 0x0, 0x0, 0xc42013b3e0)
	../vendor/github.com/codingsince1985/geo-golang/http_geocoder.go:71 +0xaa
created by ../vendor/github.com/codingsince1985/geo-golang.HTTPGeocoder.ReverseGeocode
	../vendor/github.com/codingsince1985/geo-golang/http_geocoder.go:72 +0xb7
exit status 2

**Comment by saheljalal** [comment]
Looks to be crashing on this line:
`p := r.Results[0].Locations[0]`

**Comment by manolovl** [comment]
I'm currently working on [refactoring](https://github.com/codingsince1985/geo-golang/issues/29) the library and I see I've already handled this case in my branch. Shouldn't take long to finish it up and create a PR.

**Comment by codingsince1985** [comment]
Thank you @saheljalal for heads up. Current version can handle reverse geocoding (0, 0) with no problem. I reckon server returned something else at that moment that couldn't be processed, as @manolovl has mentioned.

**Comment by codingsince1985** [comment]
@manolovl, got this when reverse geocoding (0,0)
```
{  
   "info":{  
      "statuscode":0,
      "copyright":{  
         "text":"\u00A9 2017 MapQuest, Inc.",
         "imageUrl":"http://api.mqcdn.com/res/mqlogo.gif",
         "imageAltText":"\u00A9 2017 MapQuest, Inc."
      },
      "messages":[  

      ]
   },
   "options":{  
      "maxResults":1,
      "thumbMaps":true,
      "ignoreLatLngInput":false
   },
   "results":[  
      {  
         "providedLocation":{  
            "latLng":{  
               "lat":0.0,
               "lng":0.0
            }
         },
         "locations":[  
            {  
               "street":"",
               "adminArea6":"",
               "adminArea6Type":"Neighborhood",
               "adminArea5":"",
               "adminArea5Type":"City",
               "adminArea4":"",
               "adminArea4Type":"County",
               "adminArea3":"",
               "adminArea3Type":"State",
               "adminArea1":"XZ",
               "adminArea1Type":"Country",
               "postalCode":"",
               "geocodeQualityCode":"A1XAX",
               "geocodeQuality":"COUNTRY",
               "dragPoint":false,
               "sideOfStreet":"N",
               "linkId":"0",
               "unknownInput":"",
               "type":"s",
               "latLng":{  
                  "lat":0.0,
                  "lng":0.0
               },
               "displayLatLng":{  
                  "lat":0.0,
                  "lng":0.0
               },
               "mapUrl":"http://open.mapquestapi.com/staticmap/v4/getmap?key=...&type=map&size=225,160&pois=purple-1,0.0,0.0,0,0,|&center=0.0,0.0&zoom=2&rand=-1071230176"
            }
         ]
      }
   ]
}
```
It's interesting that adminArea1="XZ" is defined in [ISO 3166](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#User-assigned_code_elements).

**Comment by manolovl** [comment]
@codingsince1985 I was just about to post the same, the response from mapquest is in my clipboard :D 
Yes, I already noticed that and changed the check of "country" / " country code" to street or similar to deduct "no result".
