### ISSUE TITLE
Panic at geo-golang/mapquest/open/geocoder.go:46

### ISSUE THREAD

**Issue by saheljalal** [codingsince1985/geo-golang#31]
Seeing another panic, not sure if it is tracked or not.

I think it's this line: 
`func (r *geocodeResponse) Location() geo.Location { return r.Results[0].Locations[0].LatLng }`

panic: runtime error: index out of range

goroutine 15 [running]:
panic(0x3a0bc0, 0xc420016100)
/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
../codingsince1985/geo-golang/mapquest/open.(*geocodeResponse).Location(0xc4204323a0, 0x6d, 0x5d32e0)
/Users/saheljalal/code/go/src/../codingsince1985/geo-golang/mapquest/open/geocoder.go:46 +0x47
../codingsince1985/geo-golang.HTTPGeocoder.Geocode.func1(0x5d4920, 0xc420017700, 0x448aa8, 0xc42014cbd0, 0x2e, 0xc420302d90)
/Users/saheljalal/code/go/src/../codingsince1985/geo-golang/http_geocoder.go:54 +0xbe
created by ../codingsince1985/geo-golang.HTTPGeocoder.Geocode
/Users/saheljalal/code/go/src/../codingsince1985/geo-golang/http_geocoder.go:55 +0xb6

**Comment by codingsince1985** [comment]
@saheljalal, it should be the same.
When you get this panic, can you please check this URL in your browser and send over the response?
`http://open.mapquestapi.com/geocoding/v1/reverse?key=YOUR_KEY&location=0,0`

**Comment by saheljalal** [comment]
@codingsince1985 i just tested by initializing all the geocoders with no env variables set (no key) and ran it with the chained geocoder with all coders passed in.  In my browser, that request gives: `The AppKey submitted with this request is invalid.`

**Comment by saheljalal** [comment]
Sample usage:

```
var geocoder *Geocoder

// Geocoder model
type Geocoder struct {
	Bing          geo.Geocoder
	Google        geo.Geocoder
	Here          geo.Geocoder
	Nominatim     geo.Geocoder
	Open          geo.Geocoder
	OpenCage      geo.Geocoder
	MapBox        geo.Geocoder
	OpenStreetMap geo.Geocoder
	LocationIQ    geo.Geocoder
}

// Chained returns a geo.Geocoder that will be chained through all geocoders
func (g *Geocoder) Chained() geo.Geocoder {
	return chained.Geocoder(g.List()...)
}

// List returns all the embedded geocoders as a list
func (g *Geocoder) List() []geo.Geocoder {
	return []geo.Geocoder{
		g.Bing,
		g.Google,
		g.Here,
		g.Nominatim,
		g.Open,
		g.OpenCage,
		g.MapBox,
		g.OpenStreetMap,
		g.LocationIQ,
	}
}

func init() {
	geocoder = &Geocoder{
		bing.Geocoder(os.Getenv("BING_API_KEY")),
		google.Geocoder(os.Getenv("GOOGLE_API_KEY")),
		here.Geocoder(os.Getenv("HERE_APP_ID"), os.Getenv("HERE_APP_CODE"), radius),
		nominatim.Geocoder(os.Getenv("MAPQUEST_NOMINATUM_KEY")),
		open.Geocoder(os.Getenv("MAPQUEST_OPEN_KEY")),
		opencage.Geocoder(os.Getenv("OPENCAGE_API_KEY")),
		mapbox.Geocoder(os.Getenv("MAPBOX_API_KEY")),
		openstreetmap.Geocoder(),
		locationiq.Geocoder(os.Getenv("LOCATIONIQ_API_KEY"), zoom),
	}
}

loc, _ := geocoder.Chained().Geocode("4100 Blackhawk Plaza Cir Danville CA 94506")
```

**Comment by codingsince1985** [comment]
Unfortunately, keys are needed for most geocoding service providers.
I'd suggest running existing tests locally first.
