### ISSUE TITLE
ReverseGeocode should return an Address struct instead of a string

### ISSUE THREAD

**Issue by saheljalal** [codingsince1985/geo-golang#32]
It would be nice if the library could parse the various mapping providers results into an Address struct or something to take away the work for clients.  Something as simple as parsing it into the following:

```
type Address struct {
	StreetAddress string
	City string
	State string
	Country string
	PostalCode string
}
```

This makes it easier to consume the API instead of doing this ourselves which is more error prone.

**Comment by manolovl** [comment]
This should have been fixed now by [PR#34](https://github.com/codingsince1985/geo-golang/pull/34)
