### ISSUE TITLE
Chained Geocoder doesn't indicate which provider was used

### ISSUE THREAD

**Issue by saheljalal** [codingsince1985/geo-golang#33]
It would be potentially useful to indicate in some way which provider successfully returned data.  If the library doesn't construct a proper address for example while reverse geocoding, that info can at least be used to help parse the returned string.

**Comment by manolovl** [comment]
Based on the argumentation, is this still desired, since we now have structured address, so no need to parse the string with flat representation of the address?

**Comment by saheljalal** [comment]
I think this would still be useful and I'm sure the information is available but closing for now since there is a solution for my original concern.
