### ISSUE TITLE
Nil results with no error

### ISSUE THREAD

**Issue by saheljalal** [codingsince1985/geo-golang#35]
I'm getting some odd results like getting a `nil` address or location when geocoding or reverse geocoding.

Geocoding "4000 Blackhawk Plaza Cir, Danville, California 94506, United States":
`[Here] Geocoded '4000 Blackhawk Plaza Cir, Danville, California 94506, United States' to location: &{37.7999631 -121.9202164}`
`[OpenCage] Failed to geocode address: geocoding error: missing API key`
`[OpenStreetMap] Failed to geocode address: location is nil`
`[Bing] Geocoded '4000 Blackhawk Plaza Cir, Danville, California 94506, United States' to location: &{37.800872802734375 -121.9173355102539}`
`[Google] Geocoded '4000 Blackhawk Plaza Cir, Danville, California 94506, United States' to location: &{37.8006389 -121.919588}`
`[Nominatim] Geocoded '4000 Blackhawk Plaza Cir, Danville, California 94506, United States' to location: &{0 0}`
`[Open] Geocoded '4000 Blackhawk Plaza Cir, Danville, California 94506, United States' to location: &{39.78373 -100.445882}`
`[MapBox] Geocoded '4000 Blackhawk Plaza Cir, Danville, California 94506, United States' to location: &{37.800639 -121.919588}`
`[LocationIQ] Failed to geocode address: location is nil`

Reverse Geocoding "37.8006389,-121.919588":
`[Google] Failed to reverse geocode location: address is nil`
`[Here] Reverse geocoded location 37.8006389,-121.919588 to 'Danville, CA 94506, United States'`
`[Open] Reverse geocoded location 37.8006389,-121.919588 to 'Blackhawk Plaza Circle, 94506, Blackhawk, CA, US'`
`[MapBox] Reverse geocoded location 37.8006389,-121.919588 to '4000 Blackhawk Plaza Cir, Danville, California 94506, United States'`
`[OpenStreetMap] Reverse geocoded location 37.8006389,-121.919588 to '4014, Blackhawk Plaza Circle, Blackhawk, Contra Costa County, California, 94506, United States of America'`
`[Bing] Reverse geocoded location 37.8006389,-121.919588 to 'Street, Danville, CA 94506'`
`[OpenCage] Failed to reverse geocode location: geocoding error: missing API key`
`[LocationIQ] Reverse geocoded location 37.8006389,-121.919588 to '4014, Blackhawk Plaza Circle, Blackhawk, Contra Costa County, California, 94506, United States of America'`
`[Nominatim] Reverse geocoded location 37.8006389,-121.919588 to 'Blackhawk Plaza Circle, Blackhawk, Contra Costa County, California, 94506, United States of America'`

I'm not sure if I'm doing something wrong or my expectation is incorrect but I would imagine we should get an error if an address or location is nil.

**Comment by saheljalal** [comment]
I just looked at the updated example code in the description and it looks like we can get a `nil` result.  I'm not sure if it's idiomatic to return a nil result without an error. Is it possible to update to provide an error in these cases so we can check for that instead of a nil result?

**Comment by manolovl** [comment]
Hi, this was one of the proposed changes in #29 (have a look at the list at the bottom). One of the points being that no results shouldn't be an error. Have a go yourself and try one of the providers, which return an error (few of them do, not all though) and send a request with the same vector directly to see that they also don't return an error. Thus the proposal to return a pointer to the structure instead of zero value to be able to distinguish no result cases. So returning `nil, nil` implies that no results have been found. To finish off, I'd claim that returning a nil pointer is idiomatic go - similar to returning... say `null` in Java.

**Comment by saheljalal** [comment]
ok makes sense, will update accordingly.

**Comment by Varentsov** [comment]
I'm using `github.com/codingsince1985/geo-golang/google` package and it is also may returns nil result with no error

`addr, err := geoCoder.ReverseGeocode(lt, lg)`

**Comment by codingsince1985** [comment]
@Varentsov, what's the lat, lng?

**Comment by Varentsov** [comment]
```
lat=51.729729729729726, lng=55.06887992842546
lat=5, lng=0
```
