### ISSUE TITLE
function openstreetmap.Geocode panics for no results query

### ISSUE THREAD

**Issue by kuba--** [codingsince1985/geo-golang#41]
For instance for address:
31171 Fisher Manor,Simeonbury,United States

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1228a40]

Because `func response` from `http_geocoder.go` returns `nil` when body is empty.

**Comment by kuba--** [comment]
suggested fix: https://github.com/codingsince1985/geo-golang/pull/40

**Comment by manolovl** [comment]
Please see issue #35 as well as my comment to PR #40. Hope it makes sense to you too.

Cheers

**Comment by kuba--** [comment]
@manolovl thanks
