### ISSUE TITLE
Mapbox reverse geocoder errors our on certain points due to literal number as `address`

### ISSUE THREAD

**Issue by ezk84** [codingsince1985/geo-golang#48]
It seems that the Mapbox Geocoding API will occasionally return the `address` field of the result as a literal number instead of the expected string encoded number (as per [this link](https://www.mapbox.com/api-documentation/#response-object)). This causes problems for the json decoder which is expecting a string. 

Here's a test case to see what I am talking about

```go
package main_test

import (
	"testing"

	"github.com/codingsince1985/geo-golang/mapbox"
)

var key string = "<your-key-here>"

func TestReverseGeocode(t *testing.T) {
	g := mapbox.Geocoder(key)
	_, err := g.ReverseGeocode(-33.932933, 150.865816)
	if err != nil {
		t.Error("Got an error:", err)
	}
}
```

I've filed a bug with Mapbox but as this may happen for more points it may be worthwhile to fix/handle in this library. At the very least it would be worthwhile to keep track of this for future devs running into this problem.

**Comment by ezk84** [comment]
The Mapbox people have got back to me and have updated their code to ensure `.address` is always returned as a string. Closing this.

**Comment by codingsince1985** [comment]
Thank you @ezk84 for the update!
