### ISSUE TITLE
Geocode should not return a nil location and a nil error

### ISSUE THREAD

**Issue by awfm9** [codingsince1985/geo-golang#57]
I just checked the openstreetmap response parser, and when the returned longitude and latitude are empty, it returns nil for both location and error.

Returning `nil` as a valid value when there is no error is undesirable. It means that we have to check the return value, regardless of whether we have a return error or not.

Instead, it would probably be good to return a sentinel error, such as `ErrNoCoordsFound`.

**Comment by codingsince1985** [comment]
i get the point of getting (nil, nil) from a function that returns (*geo.Location, error). however as a convention, we always check if err is nil first. in this case, err is nil, which means there's no error, please go ahead to check the value of *geo.Location type.
the pointer here is designed for a reason. if it's not a pointer, we may have to introduce an error to differentiate zero-ed location from got nothing. a nil pointer is enough for client to know what happened.
