### ISSUE TITLE
osm.Address struct doesn't have `hamlet` field.

### ISSUE THREAD

**Issue by 10elements** [codingsince1985/geo-golang#59]
Hi, I noticed that in the osm.Address struct, there is not `hemlet` field, if you see the response of [https://nominatim.openstreetmap.org/reverse?format=xml&lat=43.0280986&lon=-78.8136961&zoom=18&addressdetails=1](https://nominatim.openstreetmap.org/reverse?format=xml&lat=43.0280986&lon=-78.8136961&zoom=18&addressdetails=1&format=json) there is a `hemlet` field in the `address` object, can we add `Hemlet` to osm.Address struct and also add it to `func (a Address) Locality() string` as the last field to check for locality?

**Comment by codingsince1985** [comment]
thank you @10elements for the fix, #60
