### ISSUE TITLE
Geocoder interface is broken as of this morning

### ISSUE THREAD

**Issue by billykwooten** [codingsince1985/geo-golang#78]
Hello, I have a program using this package and the below line in my program is now returning errors. It was working for 5+ years until this morning.

The below is erroring out, with `city` being "New York, NY" for example as a string: 
`location, err := geocoder.Geocode(city)`

The return i'm getting is `invalid character '<' looking for beginning of value` from the Geocode interface.

**Comment by billykwooten** [comment]
Looks like nominatim requires a user agent now on the request call.

https://operations.osmfoundation.org/policies/nominatim/

**Comment by codingsince1985** [comment]
thank you @billykwooten for reporting and updating the issue.
i was thinking in the direction but couldn't pinpoint which service.
`Referer` or `User-Agent` header was required a while ago, and looks like it's mandatory now.
will fix it when i have some time.
thanks again.

**Comment by bfuller86** [comment]
I'm guessing no progress has been made on this yet, but we ran into the same issue. Seems like just adding a User-Agent header to the http request will resolve the issue with nominatim

I don't know if there's anything different about the other integrations

**Comment by ekristen** [comment]
Give this a try -- go mod edit -replace github.com/codingsince1985/geo-golang=github.com/ekristen/geo-golang@9c74285

**Comment by codingsince1985** [comment]
with @ekristen's contribution https://github.com/codingsince1985/geo-golang/pull/80 this issue is fixed in https://github.com/codingsince1985/geo-golang/releases/tag/v1.8.4
